spring:
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.data: debug
